name: Generate SBOM

on:
  push:
    branches: [ master ]

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate SBOM
        run: |
          npm install -g @cyclonedx/bom
          cyclonedx-bom -o bom.json
